### ISSUE TITLE
Overtheme improving

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#40]
When the awesome overtheme feature is used with the "copy from theme: True" option, MaTiSSe doesn't modifies the only part of the theme that the user specifies into the overtheme section, but changes all the characteristics of the object. For example, if I write

```
---
overtheme:
  - copy-from-theme: True
  - slide:
    - transition: 'diagonal'
    - content:
      - font-size: 130%
---
```

the slide attributes aren't copied from the main theme, but the slide style is reset to a "blank" style.

A very cool feature of the overtheme option could be that all the main theme characteristics are copied, except that specified in the overtheme section.
